const $=s=>document.querySelector(s);const conversation=$("#conversation"),input=$("#input"),send=$("#send"),historyEl=$("#history");let messages=[],busy=false,currentProvider=null,multiProviders=[],judgeProvider=null;const KEY="nexum-core-chats";
function save(){localStorage.setItem(KEY,JSON.stringify(messages.slice(-40)))}function load(){try{messages=JSON.parse(localStorage.getItem(KEY)||"[]")}catch{messages=[]}render();renderHistory();loadProviders()}
function render(){conversation.innerHTML="";if(!messages.length){conversation.innerHTML='<div class="welcome"><div class="welcome-mark">N</div><h1>Чем займёмся?</h1><p>Nexum Core — рабочий интерфейс для диалога с ядром, агентами и подключёнными ИИ.</p><div class="suggestions"><button data-prompt="Проанализиру структуру проекта и найди проблемы">Проанализируй проект</button><button data-prompt="Создай план разработки приложения">Составь план</button><button data-prompt="Проведи проверку доступных инструментов">Проверь инструменты</button></div></div>';return}
const wrap=document.createElement("div");wrap.className="messages";messages.forEach(m=>{const row=document.createElement("div");row.className="message "+m.role;row.innerHTML='<div class="avatar">'+(m.role==="user"?"S":"N")+'</div><div class="bubble"></div>';row.querySelector(".bubble").textContent=m.content;wrap.appendChild(row)});conversation.appendChild(wrap);conversation.scrollTop=conversation.scrollHeight}
function renderHistory(){historyEl.innerHTML="";messages.filter(m=>m.role==="user").slice(0,12).forEach(m=>{const el=document.createElement("div");el.className="history-item";el.textContent=m.content;el.onclick=()=>window.scrollTo(0,document.body.scrollHeight);historyEl.appendChild(el)})}
function add(role,content){messages.push({role,content,at:Date.now()});render();renderHistory();save()}
async function loadProviders(){try{const r=await fetch("/providers");const data=await r.json();const box=$("#providerOptions");box.innerHTML="";(data.providers||[]).forEach(p=>{const b=document.createElement("button");b.textContent=p.name+" · "+p.model;b.dataset.provider=p.name;b.onclick=()=>selectProvider(p);box.appendChild(b)})}catch{}}
function selectProvider(p){currentProvider=p.name;$("#modelButton").childNodes[0].textContent=p.name+" ";$("#modelMenu").classList.add("hidden")}
function preset(){const v=$("#providerPreset").value;const vals={openai:["OpenAI","https://api.openai.com/v1","gpt-4.1"],deepseek:["DeepSeek","https://api.deepseek.com/v1","deepseek-chat"],custom:["","",""]};const x=vals[v];$("#providerName").value=x[0];$("#providerUrl").value=x[1];$("#providerModel").value=x[2]}
async function saveProvider(){const err=$("#providerError");err.textContent="";const payload={name:$("#providerName").value.trim(),base_url:$("#providerUrl").value.trim(),model:$("#providerModel").value.trim(),api_key:$("#providerKey").value};if(!payload.name||!payload.base_url||!payload.model||!payload.api_key){err.textContent="Заполни все поля.";return}try{const r=await fetch("/providers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data.detail||"Не удалось подключить");$("#providerModal").classList.add("hidden");$("#providerKey").value="";await loadProviders();selectProvider({name:data.provider,model:data.model})}catch(e){err.textContent=e.message}}
async function openMulti(){const r=await fetch("/providers");const data=await r.json();const box=$("#multiProviders"),judge=$("#judgeProvider");box.innerHTML="";judge.innerHTML="";(data.providers||[]).forEach(p=>{const label=document.createElement("label");label.className="multi-check";label.innerHTML='<input type="checkbox" value="'+p.name+'"> '+p.name+" · "+p.model;box.appendChild(label);const o=document.createElement("option");o.value=p.name;o.textContent=p.name+" · "+p.model;judge.appendChild(o)});$("#multiModal").classList.remove("hidden")}
function saveMulti(){multiProviders=[...document.querySelectorAll("#multiProviders input:checked")].map(x=>x.value);judgeProvider=$("#judgeProvider").value||null;$("#multiModal").classList.add("hidden");$("#modelButton").childNodes[0].textContent=multiProviders.length>1?"Команда ИИ ":"Nexum Core "}
async function askMulti(text){const r=await fetch("/multi-ai/stream",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task:text.trim(),providers:multiProviders,judge:judgeProvider,context:"ui"})});if(!r.ok)throw new Error(await r.text());const reader=r.body.getReader(),decoder=new TextDecoder();let buf="",final="";while(true){const x=await reader.read();if(x.done)break;buf+=decoder.decode(x.value,{stream:true});const parts=buf.split("\n\n");buf=parts.pop()||"";for(const part of parts){const line=part.split("\n").find(x=>x.startsWith("data: "));if(!line)continue;const e=JSON.parse(line.slice(6));if(e.kind==="ai_result"){final+="\n\n["+e.provider+"]\n"+e.answer}if(e.kind==="judge_result"){final="["+e.provider+" — итог]\n"+e.answer}}}return final.trim()||"Команда не вернула ответ."}
if(busy||!text.trim())return;busy=true;send.disabled=true;add("user",text.trim());const wrap=document.createElement("div");wrap.className="messages";wrap.innerHTML='<div class="message assistant"><div class="avatar">N</div><div class="bubble"></div></div>';const bubble=wrap.querySelector(".bubble");conversation.appendChild(wrap);conversation.scrollTop=conversation.scrollHeight;let answer="";
try{if(multiProviders.length>1){const answer=await askMulti(text);wrap.remove();add("assistant",answer);return}const r=await fetch("/chat/stream",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task:text.trim(),context:"ui",provider:currentProvider})});if(!r.ok)throw new Error(await r.text());const reader=r.body.getReader(),decoder=new TextDecoder();let buf="";
while(true){const {value,done}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});const parts=buf.split("\n\n");buf=parts.pop()||"";for(const part of parts){const line=part.split("\n").find(x=>x.startsWith("data: "));if(!line)continue;const e=JSON.parse(line.slice(6));if(e.kind==="model_output"&&e.content)answer=e.content;if(e.done&&e.status==="failed")answer=e.result?.answer||"Ошибка выполнения.";if(e.kind==="tool_result"||e.kind==="verification"||e.kind==="repair"){bubble.textContent=(answer||"Выполняю задачу…")+"\n\n["+e.kind+"]";}if(e.done){answer=answer||"Задача завершена.";}}bubble.textContent=answer||"Nexum работает…";conversation.scrollTop=conversation.scrollHeight}
wrap.remove();add("assistant",answer||"Нет ответа.")}catch(e){wrap.remove();add("assistant","Ошибка соединения с Nexum Core: "+e.message)}finally{busy=false;send.disabled=false;input.focus()}}
$("#composer").addEventListener("submit",e=>{e.preventDefault();ask(input.value);input.value="";input.style.height="auto"});input.addEventListener("input",()=>{input.style.height="auto";input.style.height=Math.min(input.scrollHeight,180)+"px"});input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("#composer").requestSubmit()}});document.addEventListener("click",e=>{const p=e.target.dataset.prompt;if(p){ask(p)}});
$("#newChat").onclick=$("#newChatTop").onclick=()=>{messages=[];save();render();renderHistory();input.focus()};$("#clearHistory").onclick=()=>{messages=[];save();render();renderHistory()};
$("#menu").onclick=()=>$("#sidebar").classList.toggle("open");$("#modelButton").onclick=()=>$("#modelMenu").classList.toggle("hidden");$("#multiAI").onclick=openMulti;$("#closeMulti").onclick=()=>$("#multiModal").classList.add("hidden");$("#saveMulti").onclick=saveMulti;$("#addProvider").onclick=()=>{$("#modelMenu").classList.add("hidden");$("#providerModal").classList.remove("hidden");preset()};$("#closeProvider").onclick=()=>$("#providerModal").classList.add("hidden");$("#providerPreset").onchange=preset;$("#saveProvider").onclick=saveProvider;
async function health(){try{const r=await fetch("/health");const ok=r.ok;$("#statusDot").className="dot"+(ok?" ok":"");$("#statusText").textContent=ok?"Core онлайн":"Core недоступен"}catch{$("#statusText").textContent="Core недоступен"}}load();health();