const $=s=>document.querySelector(s);const conversation=$("#conversation"),input=$("#input"),send=$("#send"),historyEl=$("#history");let messages=[],busy=false;const KEY="nexum-core-chats";
function save(){localStorage.setItem(KEY,JSON.stringify(messages.slice(-40)))}function load(){try{messages=JSON.parse(localStorage.getItem(KEY)||"[]")}catch{messages=[]}render();renderHistory()}
function render(){conversation.innerHTML="";if(!messages.length){conversation.innerHTML='<div class="welcome"><div class="welcome-mark">N</div><h1>Чем займёмся?</h1><p>Nexum Core — рабочий интерфейс для диалога с ядром, агентами и инструментами.</p><div class="suggestions"><button data-prompt="Проанализируй структуру проекта и найди проблемы">Проанализируй проект</button><button data-prompt="Создай план разработки приложения">Составь план</button><button data-prompt="Проведи проверку доступных инструментов">Проверь инструменты</button></div></div>';return}
const wrap=document.createElement("div");wrap.className="messages";messages.forEach(m=>{const row=document.createElement("div");row.className="message "+m.role;row.innerHTML='<div class="avatar">'+(m.role==="user"?"S":"N")+'</div><div class="bubble"></div>';row.querySelector(".bubble").textContent=m.content;wrap.appendChild(row)});conversation.appendChild(wrap);conversation.scrollTop=conversation.scrollHeight}
function renderHistory(){historyEl.innerHTML="";const titles=messages.filter(m=>m.role==="user").slice(0,12);titles.forEach((m,i)=>{const el=document.createElement("div");el.className="history-item";el.textContent=m.content;el.onclick=()=>window.scrollTo(0,document.body.scrollHeight);historyEl.appendChild(el)})}
function add(role,content){messages.push({role,content,at:Date.now()});render();renderHistory();save()}
async function ask(text){if(busy||!text.trim())return;busy=true;send.disabled=true;add("user",text.trim());const wrap=document.createElement("div");wrap.className="messages";wrap.innerHTML='<div class="message assistant"><div class="avatar">N</div><div class="bubble"><div class="typing"><i></i><i></i><i></i></div></div></div>';conversation.appendChild(wrap);conversation.scrollTop=conversation.scrollHeight;try{const r=await fetch("/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task:text.trim(),context:"ui"})});const data=await r.json();const answer=data?.result?.content||data?.result?.answer||data?.error||"Нет ответа.";wrap.remove();add("assistant",answer)}catch(e){wrap.remove();add("assistant","Ошибка соединения с Nexum Core: "+e.message)}finally{busy=false;send.disabled=false;input.focus()}}
$("#composer").addEventListener("submit",e=>{e.preventDefault();ask(input.value);input.value="";input.style.height="auto"});input.addEventListener("input",()=>{input.style.height="auto";input.style.height=Math.min(input.scrollHeight,180)+"px"});input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("#composer").requestSubmit()}});document.addEventListener("click",e=>{const p=e.target.dataset.prompt;if(p){ask(p)}});
$("#newChat").onclick=$("#newChatTop").onclick=()=>{messages=[];save();render();renderHistory();input.focus()};$("#clearHistory").onclick=()=>{messages=[];save();render();renderHistory()};
$("#menu").onclick=()=>$("#sidebar").classList.toggle("open");$("#modelButton").onclick=()=>$("#modelMenu").classList.toggle("hidden");document.querySelectorAll("#modelMenu button").forEach(b=>b.onclick=()=>{$("#modelButton").childNodes[0].textContent=b.textContent+" ";$("#modelMenu").classList.add("hidden")});
async function health(){try{const r=await fetch("/health");const ok=r.ok;$("#statusDot").className="dot"+(ok?" ok":"");$("#statusText").textContent=ok?"Core онлайн":"Core недоступен"}catch{$("#statusText").textContent="Core недоступен"}}load();health();